name: CI

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * MON'

jobs:
  build:
    runs-on: macos-11
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1    
    steps:
      - name: Checkout FFmpeg/FFmpeg
        uses: eko5624/checkout@v3
        with:
          repository: "FFmpeg/FFmpeg"
          fetch-depth: 0
        
      - name: Get FFmpeg/FFmpeg last commit SHA
        id: sha
        run: echo "::set-output name=sha::$(git rev-parse --short=7 HEAD)"        

      - name: Build ffmpeg
        run: |
          brew update 
          brew install ffmpeg --HEAD
          
      - name: Zip binary packages
        run: zip -r ffmpeg-${{ steps.sha.outputs.sha }}.zip /usr/local/Cellar/ffmpeg/HEAD*

      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=date::$(date +%Y-%m-%d)"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ffmpeg-${{ steps.sha.outputs.sha }}
          name: ${{ steps.timestamp.outputs.date }}
          body: Bump to FFmpeg/FFmpeg@${{ steps.sha.outputs.sha }}
          files: ffmpeg*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
